import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/header"
import Footer from "./components/footer";

const font = Poppins({ subsets: ["latin"], weight:['400']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
